metricsInterval: 60
palladium:
  name: lipz01
  cmd: "....../WXE/23.03.s000/bin/test_server -json"
  racks:
    - name: 0
      clusterIDs: [0, 1, 2]
      boardIDs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    - name: 1
      clusterIDs: [3, 4, 5]
      boardIDs: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
zebu:
  name: zs5
  cmd: "csh -c 'source ....../zebu/S-2021.09-2/zebu_env.csh; zRscManager -sysstat ....../zebu/zebu_system_dir/zebu_system_dir_3u12m'"