{
 "title": "Palladium Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "emulator",
    "label": "emulator",
    "query": {
     "query": "label_values(palladium_status,emulator)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "palladium_status{emulator=~\"$emulator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"}) / count(palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Avg Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"}) / count(palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "Avg Utilization"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"})",
     "legendFormat": "RunningDomain"
    },
    {
     "expr": "count(palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "AllDomain"
    },
    {
     "expr": "count(palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"}) / count(palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(palladium_cluster_status{emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Boards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(palladium_cluster_board_status{emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DomainStatus",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "palladium_cluster_board_domain_status{emulator=~\"$emulator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "用户使用总时长",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(owner) (palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "用户使用Domain总数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(owner) (palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "DomainStatus",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(cluster, board) (palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(cluster, board) (palladium_cluster_board_domain_status{emulator=~\"$emulator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "用户占有资源排行",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 9, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(count by(owner) (palladium_cluster_board_domain_status{owner!=\"NONE\",emulator=~\"$emulator\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}